
export const LABOUR_LAW_CODES: string[] = [
    "The Code on Wages, 2019",
    "The Industrial Relations Code, 2020",
    "The Code on Social Security, 2020",
    "The Occupational Safety, Health and Working Conditions Code, 2020",
    "The Factories Act, 1948",
    "The Minimum Wages Act, 1948",
    "The Payment of Wages Act, 1936",
    "The Payment of Bonus Act, 1965",
    "The Equal Remuneration Act, 1976",
    "The Industrial Disputes Act, 1947",
    "The Trade Unions Act, 1926",
    "The Industrial Employment (Standing Orders) Act, 1946",
    "The Employees' Provident Funds and Miscellaneous Provisions Act, 1952",
    "The Employees' State Insurance Act, 1948",
    "The Maternity Benefit Act, 1961",
    "The Payment of Gratuity Act, 1972",
    "The Employees' Compensation Act, 1923",
    "The Building and Other Construction Workers (Regulation of Employment and Conditions of Service) Act, 1996",
    "The Unorganised Workers' Social Security Act, 2008",
    "The Plantations Labour Act, 1951",
    "The Mines Act, 1952",
    "The Dock Workers (Safety, Health and Welfare) Act, 1986",
    "The Working Journalists and Other Newspaper Employees (Conditions of Service) and Miscellaneous Provisions Act, 1955",
    "The Cine-Workers and Cinema Theatre Workers (Regulation of Employment) Act, 1981",
    "The Motor Transport Workers Act, 1961",
    "The Sales Promotion Employees (Conditions of Service) Act, 1976",
    "The Beedi and Cigar Workers (Conditions of Employment) Act, 1966",
    "The Contract Labour (Regulation and Abolition) Act, 1970",
    "The Inter-State Migrant Workmen (Regulation of Employment and Conditions of Service) Act, 1979"
];
